### ISSUE TITLE
Line does not type its material and geometry accurately in TypeScript

### ISSUE THREAD

**Issue by disambiguator** [react-spring/drei#96] opened 2020-08-24 07:33 UTC
When creating a Line and referencing it using a ref, TypeScript does not type its material and geometry as LineMaterial or LineGeometry respectively without a cast. It is otherwise typed as `Material | Material[]` and geometry as `Geometry | BufferGeometry`. Maybe there is a way within drei to type this accurately for users.

Example here:
https://github.com/disambiguator/floating_points/blob/7e9c26ee124cb92e564f51f36eb5c24509253e0d/components/cloth.tsx#L79-L81

**Comment by giulioz** [comment] 2020-08-24 10:48
This problem is caused by THREE.js typings and should be fixed in the next release: https://github.com/mrdoob/three.js/pull/20165

Feel free to open again if next THREE release doesn't solve.

**Closed by giulioz** 2020-08-24 10:48 UTC
